package com.hzjbbis.fk.message;

public class MessageConst {
    public static final byte ZJ_FUNC_RELAY = 0;
    public static final byte ZJ_FUNC_READ_CUR = 1;
    public static final byte ZJ_FUNC_READ_TASK = 2;
    public static final byte ZJ_FUNC_READ_PROG = 4;
    public static final byte ZJ_FUNC_WRITE_ROBJ = 7;
    public static final byte ZJ_FUNC_WRITE_OBJ = 8;
    public static final byte ZJ_FUNC_EXP_ALARM = 9;
    public static final byte ZJ_FUNC_ALARM_CONFIRM = 10;
    public static final byte ZJ_FUNC_USER_DEFINE = 15;
    public static final byte ZJ_FUNC_LOGIN = 33;
    public static final byte ZJ_FUNC_LOGOUT = 34;
    public static final byte ZJ_FUNC_HEART = 36;
    public static final byte ZJ_FUNC_REQ_SMS = 40;
    public static final byte ZJ_FUNC_RECV_SMS = 41;
    public static final byte DIR_DOWN = 0;
    public static final byte DIR_UP = 1;
    public static final byte GW_FUNC_REPLY = 0;
    public static final byte GW_FUNC_RESET = 1;
    public static final byte GW_FUNC_HEART = 2;
    public static final byte GW_FUNC_RELAY_CTRL = 3;
    public static final byte GW_FUNC_SETPARAM = 4;
    public static final byte GW_FUNC_CONTROL = 5;
    public static final byte GW_FUNC_AUTH = 6;
    public static final byte GW_FUNC_BAK1 = 7;
    public static final byte GW_FUNC_REQ_CASCADE_UP = 8;
    public static final byte GW_FUNC_REQ_RTU_CFG = 9;
    public static final byte GW_FUNC_GETPARAM = 10;
    public static final byte GW_FUNC_GET_TASK = 11;
    public static final byte GW_FUNC_GET_DATA1 = 12;
    public static final byte GW_FUNC_GET_DATA2 = 13;
    public static final byte GW_FUNC_GET_DATA3 = 14;
    public static final byte GW_FUNC_FILE = 15;
    public static final byte GW_FUNC_RELAY_READ = 16;
    public static final byte GW_FUNC_BAK2 = 17;
    public static final byte GW_FN_RESET = 1;
    public static final byte GW_FN_USER = 4;
    public static final byte GW_FN_HEART = 9;
    public static final byte GW_FN_LEVEL1 = 10;
    public static final byte GW_FN_LEVEL2 = 11;
}