package com.hisun.atc;

import com.hisun.constants.HiAppConstants;

public class HiATCConstants
  implements HiAppConstants
{
  public static final int SUCC = 0;
  public static final int ERR = -1;
  public static final int EOF = 1;
  public static final int NEXIST = 1;
  public static final int DUP_REC = 1;
  public static final int NFND_REC = 2;
  public static final int HAS_ERR = 2;
  public static final String HTXN_STS = "HTXN_STS";
  public static final String TTXN_STS = "TTXN_STS";
  public static final String TXN_STS = "TXN_STS";
  public static final String LOG_NO = "LOG_NO";
  public static final String MSG_TYP = "MSG_TYP";
  public static final String HRSP_CD = "HRSP_CD";
  public static final String FRSP_CD = "FRSP_CD";
  public static final String TRSP_CD = "TRSP_CD";
  public static final String RSP_CD = "RSP_CD";
  public static final String MSG_CD = "MSG_CD";
  public static final String BR_NO = "BR_NO";
  public static final String SEL_VAL = "SEL_VAL";
  public static final String SYS_ID = "SYS_ID";
  public static final String ACC_DT = "ACC_DT";
  public static final String APP_SUB = "APP_SUB";
  public static final String APP_CLS = "APP_CLS";
  public static final String BR_SEQ = "BR_SEQ";
  public static final String BR_NM = "BR_NM";
  public static final String BUS_TYP = "BUS_TYP";
  public static final String BUS_SUB = "BUS_SUB";
  public static final String MST_CHK = "MST_CHK";
  public static final String ITG_TYP = "ITG_TYP";
  public static final String TXN_TYP = "TXN_TYP";
  public static final String FIL_LIN = "FIL_LIN";
  public static final String FIL_BYT = "FIL_BYT";
  public static final String REC_NUM = "REC_NUM";
  public static final String AC_NO = "AC_NO";
  public static final String CRD_NO = "CRD_NO";
  public static final String ORG_NO = "ORG_NO";
  public static final String NOD_NO = "NOD_NO";
  public static final String NOD_TRC = "NOD_TRC";
  public static final String HLOG_NO = "HLOG_NO";
  public static final String TCK_NO = "TCK_NO";
  public static final String TCUS_NM = "TCUS_NM";
  public static final String TCUS_ID = "TCUS_ID";
  public static final String TACC_DT = "TACC_DT";
  public static final String TLOG_NO = "TLOG_NO";
  public static final String OLOG_NO = "OLOG_NO";
  public static final String TIA_TYP = "TIA_TYP";
  public static final String TLR_ID = "TLR_ID";
  public static final String PAG_NO = "PAG_NO";
  public static final String PAG_IDX = "PAG_IDX";
  public static final String APP_ID = "APP_ID";
  public static final String APP_NM = "APP_NM";
  public static final String APP_NUM = "APP_NUM";
  public static final String RPT_ID = "RPT_ID";
  public static final String RPT_NM = "RPT_NM";
  public static final String RPT_ATR = "RPT_ATR";
  public static final String CNL_SUB = "CNL_SUB";
  public static final String TXN_CNL = "TXN_CNL";
  public static final String TRAN_ID = "TRAN_ID";
  public static final String CRP_CD = "CRP_CD";
  public static final String DSK_NO = "DSK_NO";
  public static final String DSK_NM = "DSK_NM";
  public static final String STS = "STS";
  public static final String TXN_SQN = "TXN_SQN";
  public static final String CHK_FLG = "CHK_FLG";
  public static final String SUM_FLG = "SUM_FLG";
  public static final String UPD_FLG = "UPD_FLG";
  public static final String NODEL_FLG = "NODEL_FLG";
  public static final String ORN_CNT = "ORN_CNT";
  public static final String ORN_AMT = "ORN_AMT";
  public static final String STOP = "STOP";
  public static final String SIGN = "SIGN";
  public static final String SUM = "SUM";
  public static final String HPR_CHK = "HPR_CHK";
  public static final String LST_CHK = "LST_CHK";
  public static final String IS_TXN = "IS_TXN";
  public static final String TXN_AMT = "TXN_AMT";
  public static final String JUMP = "JUMP";
  public static final String FIL_NM = "FIL_NM";
  public static final String TXN_CD = "TXN_CD";
}